{% set version = "1.0.1" %}

package:
  name: escapism
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/e/escapism/escapism-{{ version }}.tar.gz
  sha256: 73256bdfb4f22230f0428fc6efecee61cdc4fad531b6f98b849cb9c80711e4ec

build:
  number: 0
  noarch: python
  script: '{{ PYTHON }} -m pip install . --no-deps --ignore-installed --no-cache-dir -vvv '

requirements:
  host:
    - pip
    - python
  run:
    - python

test:
  imports:
    - escapism

about:
  home: https://github.com/minrk/escapism
  license: MIT
  license_family: MIT
  license_file: LICENSE
  summary: Simple, generic API for escaping strings

extra:
  recipe-maintainers:
    - ocefpaf
