{% set version = "1.1.0" %}

package:
  name: escapism
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/e/escapism/escapism-{{ version }}.tar.gz
  sha256: add130e48a85bb1aaea3e74fb031f5033c7055aedb39a3265f923d5f40c3f974

build:
  number: 0
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation

requirements:
  host:
    - python
    - setuptools
    - pip
  run:
    - python

test:
  imports:
    - escapism
  commands:
    - pip check
  requires:
    - pip
    - python

about:
  home: https://github.com/minrk/escapism
  dev_url: https://github.com/minrk/escapism
  doc_url: https://pypi.org/project/escapism/
  license: MIT
  license_family: MIT
  license_file: LICENSE
  summary: Simple, generic API for escaping strings
  description: |
    Escapism is a small library that offers a simple, generic API for escaping
    strings so they are safe to use in contexts such as URLs, filenames, or
    other structured text.

extra:
  recipe-maintainers:
    - ocefpaf
