travis:
  secure:
    BINSTAR_TOKEN: j86bgdlbWeBtJclp6dvhvTHPTvrmmbnSnk+9RH8uenHMU8PBaKgIJ/SfgsWTHpxDaz28bgAP1uGAS6R9i0zV9CrxyixtL6GTCyeXKCSAOi5Uj4WGsR1CC9cvhSctylqlfp2+Isc0a4yF2a1wmY9pAGvlwGhtRtaNzdEtlcEWIoIcUhhTn1oeIl1ZTeZqWgWo3WGMnNaKxTTYSZW1+xY4QjBz+Q8MHk51/wA/xSngQOpSGHvoz6wb3K7h/LGmyQSuxQQVu8D7qjFfjI8GfqgILG5ocDwFiKLF7Ib2tYB/WgQpvRWQAv/M6l46IE23im0yCKxy8arZja0seF5RkiDXKk+NybAykDVFcfWP51G5c8ZHy1O2WGD+C9n2Iyv3oVEeuph71KKADQkzrTfb7XUmm0cTj01CThB2OqusCVtL5ww2iwuJdXPkh5rEJSVUjN4mJk09HIV5P2v+/yDAiEfFZZahbZXetUtz2M+WNTECt9/vbA2GD/aJUT9QlMGJWIbqhqd99R+fYOuaSU1jeMbZ1QQGr1X2SDp5FLSZ7Fj3TawxLlM3WBgDD98eS7KNp339P5taB/8+5LCU5WapiLlszKVrANtHVIrN8zwwPQ6CE3TUVoAa5u/UTfVzGBQxmU5PaC/1eUZWmB50eWwSbkUWpfI8pRNhVq5/6u+oKqUqdxk=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
